services:
  data-proxy:
    build:
      context: ./data-proxy
      dockerfile: Dockerfile
      args:
        - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
        - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    # ports:
    #   - "8080:80"
    environment:
      - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
      - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    depends_on:
      data:
        condition: service_healthy

  front:
    build:
      # docker build --build-arg DATABASE_URL=postgresql://endquote@host.docker.internal:5432/endquote -t endquote-front -f Dockerfile .
      # docker run -p 3000:3000 -p 5555:5555 -e DATABASE_URL=postgresql://endquote@host.docker.internal:5432/endquote endquote-front
      context: ./front
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NUXT_PUBLIC_HOSTNAME=endquote.com
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # ports:
    #   - "3000:3000"
    #   - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
  front-redirect:
    image: cusspvz/redirect
    environment:
      - REDIRECT=https://endquote.com
    depends_on:
      front:
        condition: service_healthy
