services:
  data:
    build:
      # docker build -t endquote-back -f Dockerfile .
      context: ./data
      dockerfile: Dockerfile
    container_name: data
    # ports:
    #   - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FS_API_KEY=${FS_API_KEY}
      - FS_SERVICE_KEY=${FS_SERVICE_KEY}
      - FS_CLIENT_ID=${FS_CLIENT_ID}
      - FS_CLIENT_SECRET=${FS_CLIENT_SECRET}
      - FS_REDIRECT_URI=${FS_REDIRECT_URI}
      - FS_ACCESS_TOKEN=${FS_ACCESS_TOKEN}
      - MICHELIN_USER=${MICHELIN_USER}
      - MICHELIN_PASS=${MICHELIN_PASS}

  data-proxy:
    build:
      context: ./data-proxy
      dockerfile: Dockerfile
      args:
        - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
        - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    container_name: data-proxy
    # ports:
    #   - "8080:80"
    environment:
      - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
      - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    depends_on:
      - data

  front:
    build:
      # docker build --build-arg DATABASE_URL=postgresql://endquote@host.docker.internal:5432/endquote -t endquote-front -f Dockerfile .
      context: ./front
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: front
    # ports:
    #   - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  front-redirect:
    image: cusspvz/redirect
    environment:
      - REDIRECT=https://endquote.com
    depends_on:
      - front
