services:
  database:
    image: postgres:17
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - FS_API_KEY=${FS_API_KEY}
      - FS_SERVICE_KEY=${FS_SERVICE_KEY}
      - FS_CLIENT_ID=${FS_CLIENT_ID}
      - FS_CLIENT_SECRET=${FS_CLIENT_SECRET}
      - FS_REDIRECT_URI=${FS_REDIRECT_URI}
      - FS_ACCESS_TOKEN=${FS_ACCESS_TOKEN}
      - MICHELIN_USER=${MICHELIN_USER}
      - MICHELIN_PASS=${MICHELIN_PASS}
    depends_on:
      - database

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      - database
