services:
  data:
    build:
      # docker build -t endquote-back -f Dockerfile .
      context: ./data
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # ports:
    #   - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FS_API_KEY=${FS_API_KEY}
      - FS_SERVICE_KEY=${FS_SERVICE_KEY}
      - FS_CLIENT_ID=${FS_CLIENT_ID}
      - FS_CLIENT_SECRET=${FS_CLIENT_SECRET}
      - FS_REDIRECT_URI=${FS_REDIRECT_URI}
      - FS_ACCESS_TOKEN=${FS_ACCESS_TOKEN}
      - MICHELIN_USER=${MICHELIN_USER}
      - MICHELIN_PASS=${MICHELIN_PASS}

  data-proxy:
    build:
      context: ./data-proxy
      dockerfile: Dockerfile
      args:
        - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
        - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    # ports:
    #   - "8080:80"
    environment:
      - DATA_BASIC_AUTH_USER=${DATA_BASIC_AUTH_USER}
      - DATA_BASIC_AUTH_PASS=${DATA_BASIC_AUTH_PASS}
    depends_on:
      data:
        condition: service_healthy

  front:
    build:
      # docker build --build-arg DATABASE_URL=postgresql://endquote@host.docker.internal:5432/endquote -t endquote-front -f Dockerfile .
      context: ./front
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # ports:
    #   - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_PUBLIC_HOSTNAME=endquote.com
      - NUXT_API_SECRET=foo
      - NUXT_PUBLIC_API_BASE=bar
  front-redirect:
    image: cusspvz/redirect
    environment:
      - REDIRECT=https://endquote.com
    depends_on:
      front:
        condition: service_healthy
