services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FS_API_KEY=${FS_API_KEY}
      - FS_SERVICE_KEY=${FS_SERVICE_KEY}
      - FS_CLIENT_ID=${FS_CLIENT_ID}
      - FS_CLIENT_SECRET=${FS_CLIENT_SECRET}
      - FS_REDIRECT_URI=${FS_REDIRECT_URI}
      - FS_ACCESS_TOKEN=${FS_ACCESS_TOKEN}
      - MICHELIN_USER=${MICHELIN_USER}
      - MICHELIN_PASS=${MICHELIN_PASS}

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  redirect:
    image: cusspvz/redirect
    ports:
      - "80:80"
    environment:
      - REDIRECT=https://endquote.com
